"""bug fix for goods 3

Revision ID: 4adbea7b10b4
Revises: ddbcb2431259
Create Date: 2024-05-11 16:46:34.555215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4adbea7b10b4'
down_revision: Union[str, None] = 'ddbcb2431259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
